name: Change Title and Lint HTML

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'New title for the HTML page'
        required: true
        default: 'New Page Title'

jobs:
  update_and_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change HTML Title
      run: |
        NEW_TITLE="${{ github.event.inputs.title }}"
        sed -i "s/<title>.*<\/title>/<title>$NEW_TITLE<\/title>/" index.html

    - name: Run HTML Linter
      uses: reviewdog/action-htmlhint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-check
